// <auto-generated />
using System;
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Solution.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20220401220239_AddAnimalPhotoURL")]
    partial class AddAnimalPhotoURL
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AdoptionPrice")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("AnimalPhotoURL")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("DateListed")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("GoodWithChildren")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("GoodWithOtherAnimals")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            AdoptionPrice = 500,
                            Age = 6,
                            Breed = "Beagle",
                            DateListed = new DateTime(2022, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Female",
                            GoodWithChildren = true,
                            GoodWithOtherAnimals = true,
                            Name = "Babby",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 2,
                            AdoptionPrice = 800,
                            Age = 1,
                            Breed = "Beagle",
                            DateListed = new DateTime(2022, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            GoodWithChildren = false,
                            GoodWithOtherAnimals = true,
                            Name = "Billy",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 3,
                            AdoptionPrice = 200,
                            Age = 9,
                            Breed = "German Schnauzer",
                            DateListed = new DateTime(2021, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            GoodWithChildren = true,
                            GoodWithOtherAnimals = false,
                            Name = "Ned",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 4,
                            AdoptionPrice = 100,
                            Age = 2,
                            Breed = "Mutt",
                            DateListed = new DateTime(2021, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Female",
                            GoodWithChildren = false,
                            GoodWithOtherAnimals = true,
                            Name = "Poppins",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 5,
                            AdoptionPrice = 800,
                            Age = 0,
                            Breed = "Pomeranian",
                            DateListed = new DateTime(2022, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Female",
                            GoodWithChildren = true,
                            GoodWithOtherAnimals = true,
                            Name = "Mr Scruffles",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 6,
                            AdoptionPrice = 70,
                            Age = 15,
                            Breed = "Tabby",
                            DateListed = new DateTime(2020, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            GoodWithChildren = false,
                            GoodWithOtherAnimals = false,
                            Name = "Tabatha",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 7,
                            AdoptionPrice = 300,
                            Age = 0,
                            Breed = "Calico",
                            DateListed = new DateTime(2022, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Female",
                            GoodWithChildren = false,
                            GoodWithOtherAnimals = false,
                            Name = "Pepper",
                            Species = "Cat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
